# city_group_usernames.py

# Словарь, где ключ — кортеж (страна, город), а значение — username группы Telegram (без "@")
CITY_GROUP_USERNAMES = {
    ("Германия", "Гельдерн"): "zhivuv_gelderne",

    # Дополнения:
    CITY_GROUP_USERNAMES = ({
    ("Азербайджан", "Агдам"): "zhivuv_agdam",
    ("Азербайджан", "Агдаш"): "zhivuv_agdash",
    ("Азербайджан", "Агджабеди"): "zhivuv_agdzhabedi",
    ("Азербайджан", "Агстафа"): "zhivuv_agstafa",
    ("Азербайджан", "Астара"): "zhivuv_astara",
    ("Азербайджан", "Баку"): "zhivuv_baku",
    ("Азербайджан", "Барда"): "zhivuv_barda",
    ("Азербайджан", "Бейлаган"): "zhivuv_beilagan",
    ("Азербайджан", "Балакен"): "zhivuv_balaken",
    ("Азербайджан", "Гянджа"): "zhivuv_gyandzha",
    ("Азербайджан", "Гобустан"): "zhivuv_gobustan",
    ("Азербайджан", "Губа"): "zhivuv_guba",
    ("Азербайджан", "Горадаг"): "zhivuv_goradag",
    ("Азербайджан", "Гёйчай"): "zhivuv_geichai",
    ("Азербайджан", "Закаталы"): "zhivuv_zakataly",
    ("Азербайджан", "Загатала"): "zhivuv_zagatala",
    ("Азербайджан", "Зардоб"): "zhivuv_zardob",
    ("Азербайджан", "Имирли"): "zhivuv_imirli",
    ("Азербайджан", "Имишли"): "zhivuv_imishli",
    ("Азербайджан", "Кельбаджар"): "zhivuv_kelbadzhar",
    ("Азербайджан", "Кусары"): "zhivuv_kusary",
    ("Азербайджан", "Кюрдамир"): "zhivuv_kyurdamir",
    ("Азербайджан", "Ленкорань"): "zhivuv_lenkoran",
    ("Азербайджан", "Мингечаур"): "zhivuv_mingechaur",
    ("Азербайджан", "Нафталан"): "zhivuv_naftalan",
    ("Азербайджан", "Нахичевань"): "zhivuv_nahichevan",
    ("Азербайджан", "Нефтечала"): "zhivuv_neftechala",
    ("Азербайджан", "Огуз"): "zhivuv_oguz",
    ("Азербайджан", "Саатлы"): "zhivuv_saatly",
    ("Азербайджан", "Сабирабад"): "zhivuv_sabirabad",
    ("Азербайджан", "Сальян"): "zhivuv_salyan",
    ("Азербайджан", "Самух"): "zhivuv_samuh",
    ("Азербайджан", "Сумгаит"): "zhivuv_sumgait",
    ("Азербайджан", "Тертер"): "zhivuv_terter",
    ("Азербайджан", "Товуз"): "zhivuv_tovuz",
    ("Азербайджан", "Уджары"): "zhivuv_udzhary",
    ("Азербайджан", "Физули"): "zhivuv_fizuli",
    ("Азербайджан", "Хачмаз"): "zhivuv_hachmaz",
    ("Азербайджан", "Ходжавенд"): "zhivuv_hodzhavend",
    ("Азербайджан", "Худат"): "zhivuv_hudat",
    ("Азербайджан", "Хызы"): "zhivuv_hyzy",
    ("Азербайджан", "Шамкир"): "zhivuv_shamkir",
    ("Азербайджан", "Шарур"): "zhivuv_sharur",
    ("Азербайджан", "Шеки"): "zhivuv_sheki",
    ("Азербайджан", "Шемаха"): "zhivuv_shemaha",
    ("Азербайджан", "Ширван"): "zhivuv_shirvan",
    ("Азербайджан", "Шуша"): "zhivuv_shusha",
    ("Азербайджан", "Ярдымлы"): "zhivuv_yardymly",
    ("Азербайджан", "Исмаиллы"): "zhivuv_ismailly"
})
CITY_GROUP_USERNAMES.update({
    ("Армения", "Абовян"): "zhivuv_abovyan",
    ("Армения", "Айрум"): "zhivuv_airum",
    ("Армения", "Алагёз"): "zhivuv_alagez",
    ("Армения", "Алаверди"): "zhivuv_alaverdi",
    ("Армения", "Ани"): "zhivuv_ani",
    ("Армения", "Арагац"): "zhivuv_aragats",
    ("Армения", "Арарат"): "zhivuv_ararat",
    ("Армения", "Артик"): "zhivuv_artik",
    ("Армения", "Армавир"): "zhivuv_armavir",
    ("Армения", "Артаваз"): "zhivuv_artavaz",
    ("Армения", "Арцни"): "zhivuv_artsni",
    ("Армения", "Аштарак"): "zhivuv_ashtarak",
    ("Армения", "Бюрегаван"): "zhivuv_byuregavan",
    ("Армения", "Берд"): "zhivuv_berd",
    ("Армения", "Вагаршапат"): "zhivuv_vagarshapat",
    ("Армения", "Ванадзор"): "zhivuv_vanadzor",
    ("Армения", "Веди"): "zhivuv_vedi",
    ("Армения", "Гавар"): "zhivuv_gavar",
    ("Армения", "Гарни"): "zhivuv_garni",
    ("Армения", "Геховит"): "zhivuv_gehovit",
    ("Армения", "Гехаркуник"): "zhivuv_geharkunik",
    ("Армения", "Горис"): "zhivuv_goris",
    ("Армения", "Гюмри"): "zhivuv_gyumri",
    ("Армения", "Джермук"): "zhivuv_dzhermuk",
    ("Армения", "Дилижан"): "zhivuv_dilizhan",
    ("Армения", "Егвард"): "zhivuv_egvard",
    ("Армения", "Ерасх"): "zhivuv_erash",
    ("Армения", "Ереван"): "zhivuv_erevan",
    ("Армения", "Ехегнадзор"): "zhivuv_ehegnadzor",
    ("Армения", "Зовун"): "zhivuv_zovun",
    ("Армения", "Иджеван"): "zhivuv_idzhevan",
    ("Армения", "Капан"): "zhivuv_kapan",
    ("Армения", "Маралик"): "zhivuv_maralik",
    ("Армения", "Масис"): "zhivuv_masis",
    ("Армения", "Мартуни"): "zhivuv_martuni",
    ("Армения", "Мецамор"): "zhivuv_metsamor",
    ("Армения", "Ноемберян"): "zhivuv_noemberyan",
    ("Армения", "Нор Ачин"): "zhivuv_nor_achin",
    ("Армения", "Нор Хачн"): "zhivuv_nor_hachn",
    ("Армения", "Раздан"): "zhivuv_razdan",
    ("Армения", "Севан"): "zhivuv_sevan",
    ("Армения", "Сисиан"): "zhivuv_sisian",
    ("Армения", "Спитак"): "zhivuv_spitak",
    ("Армения", "Степанаван"): "zhivuv_stepanavan",
    ("Армения", "Талин"): "zhivuv_talin",
    ("Армения", "Ташир"): "zhivuv_tashir",
    ("Армения", "Чаренцаван"): "zhivuv_charentsavan",
    ("Армения", "Цахкадзор"): "zhivuv_tsahkadzor",
    ("Армения", "Цнори"): "zhivuv_tsnori",
    ("Армения", "Шнох"): "zhivuv_shnoh",
    ("Армения", "Шемокмеди"): "zhivuv_shemokmedi",
    ("Армения", "Ширак"): "zhivuv_shirak"
})
CITY_GROUP_USERNAMES.update({
    ("Германия", "Аугсбург"): "zhivuv_augsburg",
    ("Германия", "Берлин"): "zhivuv_berlin",
    ("Германия", "Билефельд"): "zhivuv_bielefeld",
    ("Германия", "Бонн"): "zhivuv_bonn",
    ("Германия", "Бохум"): "zhivuv_bochum",
    ("Германия", "Брауншвейг"): "zhivuv_braunschweig",
    ("Германия", "Бремен"): "zhivuv_bremen",
    ("Германия", "Висбаден"): "zhivuv_wiesbaden",
    ("Германия", "Вольфсбург"): "zhivuv_wolfsburg",
    ("Германия", "Вупперталь"): "zhivuv_wuppertal",
    ("Германия", "Ганновер"): "zhivuv_hannover",
    ("Германия", "Гельзенкирхен"): "zhivuv_gelsenkirchen",
    ("Германия", "Гельдерн"): "zhivuv_gelderne",
    ("Германия", "Гера"): "zhivuv_gera",
    ("Германия", "Гёттинген"): "zhivuv_goettingen",
    ("Германия", "Дортмунд"): "zhivuv_dortmund",
    ("Германия", "Дрезден"): "zhivuv_dresden",
    ("Германия", "Дюссельдорф"): "zhivuv_duesseldorf",
    ("Германия", "Зарбрюкен"): "zhivuv_saarbruecken",
    ("Германия", "Зиген"): "zhivuv_siegen",
    ("Германия", "Кассель"): "zhivuv_kassel",
    ("Германия", "Кёльн"): "zhivuv_koeln",
    ("Германия", "Киль"): "zhivuv_kiel",
    ("Германия", "Кобленц"): "zhivuv_koblenz",
    ("Германия", "Крефельд"): "zhivuv_krefeld",
    ("Германия", "Любек"): "zhivuv_luebeck",
    ("Германия", "Майнц"): "zhivuv_mainz",
    ("Германия", "Мангейм"): "zhivuv_mannheim",
    ("Германия", "Мюнстер"): "zhivuv_muenster",
    ("Германия", "Мюнхен"): "zhivuv_muenchen",
    ("Германия", "Нюрнберг"): "zhivuv_nuernberg",
    ("Германия", "Ольденбург"): "zhivuv_oldenburg",
    ("Германия", "Потсдам"): "zhivuv_potsdam",
    ("Германия", "Регенсбург"): "zhivuv_regensburg",
    ("Германия", "Росток"): "zhivuv_rostock",
    ("Германия", "Штутгарт"): "zhivuv_stuttgart",
    ("Германия", "Фрайбург"): "zhivuv_freiburg",
    ("Германия", "Франкфурт-на-Майне"): "zhivuv_frankfurt",
    ("Германия", "Хаген"): "zhivuv_hagen",
    ("Германия", "Хайльбронн"): "zhivuv_heilbronn",
    ("Германия", "Хамм"): "zhivuv_hamm",
    ("Германия", "Хемниц"): "zhivuv_chemnitz",
    ("Германия", "Цвиккау"): "zhivuv_zwickau",
    ("Германия", "Эрфурт"): "zhivuv_erfurt",
    ("Германия", "Эссен"): "zhivuv_essen",
    ("Германия", "Ахен"): "zhivuv_aachen",
    ("Германия", "Ханау"): "zhivuv_hanau",
    ("Германия", "Херне"): "zhivuv_herne",
    ("Германия", "Золинген"): "zhivuv_solingen",
    ("Германия", "Ульм"): "zhivuv_ulm"
})
CITY_GROUP_USERNAMES.update({
    ("Грузия", "Ахалцихе"): "zhivuv_akhaltsikhe",
    ("Грузия", "Ахалкалаки"): "zhivuv_akhalakalaki",
    ("Грузия", "Батуми"): "zhivuv_batumi",
    ("Грузия", "Болниси"): "zhivuv_bolnisi",
    ("Грузия", "Вале"): "zhivuv_vale",
    ("Грузия", "Гардабани"): "zhivuv_gardabani",
    ("Грузия", "Гори"): "zhivuv_gori",
    ("Грузия", "Гурджаани"): "zhivuv_gurjaani",
    ("Грузия", "Дедоплисцкаро"): "zhivuv_dedoplistskaro",
    ("Грузия", "Дманиси"): "zhivuv_dmanisi",
    ("Грузия", "Душети"): "zhivuv_dusheti",
    ("Грузия", "Зестафони"): "zhivuv_zestafoni",
    ("Грузия", "Зугдиди"): "zhivuv_zugdidi",
    ("Грузия", "Каспи"): "zhivuv_kaspi",
    ("Грузия", "Кварели"): "zhivuv_kvareli",
    ("Грузия", "Кобулети"): "zhivuv_kobuleti",
    ("Грузия", "Лагодехи"): "zhivuv_lagodekhi",
    ("Грузия", "Ланчхути"): "zhivuv_lanchkhuti",
    ("Грузия", "Марнеули"): "zhivuv_marneuli",
    ("Грузия", "Мартвили"): "zhivuv_martvili",
    ("Грузия", "Озургети"): "zhivuv_ozurgeti",
    ("Грузия", "Он"): "zhivuv_on",
    ("Грузия", "Поти"): "zhivuv_poti",
    ("Грузия", "Рустави"): "zhivuv_rustavi",
    ("Грузия", "Сагареджо"): "zhivuv_sagarejo",
    ("Грузия", "Самтредиа"): "zhivuv_samtredia",
    ("Грузия", "Сенаке"): "zhivuv_senaki",
    ("Грузия", "Сигнахи"): "zhivuv_signagi",
    ("Грузия", "Телави"): "zhivuv_telavi",
    ("Грузия", "Тетри-Цкаро"): "zhivuv_tetri_tskaro",
    ("Грузия", "Ткибули"): "zhivuv_tkibuli",
    ("Грузия", "Тбилиси"): "zhivuv_tbilisi",
    ("Грузия", "Цаленджиха"): "zhivuv_tsalenjikha",
    ("Грузия", "Цалки"): "zhivuv_tsalki",
    ("Грузия", "Цнори"): "zhivuv_tsnori",
    ("Грузия", "Цхалтубо"): "zhivuv_tskaltubo",
    ("Грузия", "Цхинвали"): "zhivuv_tskhinvali",
    ("Грузия", "Чакви"): "zhivuv_chakvi",
    ("Грузия", "Чиатура"): "zhivuv_chiatura",
    ("Грузия", "Чохатаури"): "zhivuv_chokhatauri",
    ("Грузия", "Шаумяни"): "zhivuv_shaumyani",
    ("Грузия", "Шемокмеди"): "zhivuv_shemokmedi",
    ("Грузия", "Шоропани"): "zhivuv_shoropani",
    ("Грузия", "Хашури"): "zhivuv_khashuri",
    ("Грузия", "Хоби"): "zhivuv_khobi",
    ("Грузия", "Хони"): "zhivuv_khoni",
    ("Грузия", "Хуло"): "zhivuv_khulo",
    ("Грузия", "Цителцкаро"): "zhivuv_tsiteltskaro",
    ("Грузия", "Кутаиси"): "zhivuv_kutaisi"
})
CITY_GROUP_USERNAMES.update({
    ("Израиль", "Акко"): "zhivuv_akko",
    ("Израиль", "Арад"): "zhivuv_arad",
    ("Израиль", "Ашдод"): "zhivuv_ashdod",
    ("Израиль", "Ашкелон"): "zhivuv_ashkelon",
    ("Израиль", "Бат-Ям"): "zhivuv_bat_yam",
    ("Израиль", "Беэр-Шева"): "zhivuv_beer_sheva",
    ("Израиль", "Бней-Брак"): "zhivuv_bnei_brak",
    ("Израиль", "Герцлия"): "zhivuv_herzliya",
    ("Израиль", "Гиватаим"): "zhivuv_givataim",
    ("Израиль", "Гуш-Дан"): "zhivuv_gush_dan",
    ("Израиль", "Димона"): "zhivuv_dimona",
    ("Израиль", "Йерухам"): "zhivuv_yeruham",
    ("Израиль", "Кармиэль"): "zhivuv_karmiel",
    ("Израиль", "Кирьят-Шмона"): "zhivuv_kiryat_shmona",
    ("Израиль", "Кирьят-Ата"): "zhivuv_kiryat_ata",
    ("Израиль", "Кирьят-Бялик"): "zhivuv_kiryat_bialik",
    ("Израиль", "Кирьят-Малахи"): "zhivuv_kiryat_malakhi",
    ("Израиль", "Кирьят-Моцкин"): "zhivuv_kiryat_motskin",
    ("Израиль", "Кирьят-Ям"): "zhivuv_kiryat_yam",
    ("Израиль", "Лод"): "zhivuv_lod",
    ("Израиль", "Маале-Адумим"): "zhivuv_maale_adumim",
    ("Израиль", "Мигдаль"): "zhivuv_migdal",
    ("Израиль", "Модин"): "zhivuv_modiin",
    ("Израиль", "Нагария"): "zhivuv_nahariya",
    ("Израиль", "Назрет"): "zhivuv_nazareth",
    ("Израиль", "Нахалаль"): "zhivuv_nahalal",
    ("Израиль", "Нешер"): "zhivuv_nesher",
    ("Израиль", "Нетания"): "zhivuv_netanya",
    ("Израиль", "Нетивот"): "zhivuv_netivot",
    ("Израиль", "Офаким"): "zhivuv_ofakim",
    ("Израиль", "Пардес-Хана"): "zhivuv_pardes_hana",
    ("Израиль", "Петах-Тиква"): "zhivuv_petah_tikva",
    ("Израиль", "Рамат-Ган"): "zhivuv_ramat_gan",
    ("Израиль", "Рамат-Ха-Шарон"): "zhivuv_ramat_hasharon",
    ("Израиль", "Реховот"): "zhivuv_rehovot",
    ("Израиль", "Рош-ха-Аин"): "zhivuv_rosh_haayin",
    ("Израиль", "Сдерот"): "zhivuv_sderot",
    ("Израиль", "Тель-Авив"): "zhivuv_tel_aviv",
    ("Израиль", "Тверия"): "zhivuv_tiberias",
    ("Израиль", "Ум-эль-Фахм"): "zhivuv_um_el_fahm",
    ("Израиль", "Хайфа"): "zhivuv_haifa",
    ("Израиль", "Хадера"): "zhivuv_hadera",
    ("Израиль", "Холон"): "zhivuv_holon",
    ("Израиль", "Шохам"): "zhivuv_shoham",
    ("Израиль", "Явне"): "zhivuv_yavne",
    ("Израиль", "Яффо"): "zhivuv_jaffa",
    ("Израиль", "Кацрин"): "zhivuv_katzrin",
    ("Израиль", "Йокнеам"): "zhivuv_yokneam",
    ("Израиль", "Бейт-Шемеш"): "zhivuv_beit_shemesh",
    ("Израиль", "Бейт-Ян"): "zhivuv_beit_yan"
})
CITY_GROUP_USERNAMES.update({
    ("Мексика", "Агуаскальентес"): "zhivuv_aguaskalientes",
    ("Мексика", "Акапулько"): "zhivuv_akapulko",
    ("Мексика", "Аподака"): "zhivuv_apodaka",
    ("Мексика", "Ацтек"): "zhivuv_aztek",
    ("Мексика", "Веракрус"): "zhivuv_verakrus",
    ("Мексика", "Гвадалахара"): "zhivuv_gvadalakhara",
    ("Мексика", "Герреро"): "zhivuv_gerero",
    ("Мексика", "Гомес-Паласио"): "zhivuv_gomes_palasio",
    ("Мексика", "Гуанахуато"): "zhivuv_guanakhuato",
    ("Мексика", "Дуранго"): "zhivuv_durango",
    ("Мексика", "Ирапуато"): "zhivuv_irapuato",
    ("Мексика", "Канкун"): "zhivuv_kankun",
    ("Мексика", "Керетаро"): "zhivuv_keretaro",
    ("Мексика", "Коацакоалькос"): "zhivuv_koatsakoalkos",
    ("Мексика", "Куэрнавака"): "zhivuv_kuernavaka",
    ("Мексика", "Леон"): "zhivuv_leon",
    ("Мексика", "Матаморос"): "zhivuv_matamoros",
    ("Мексика", "Мерида"): "zhivuv_merida",
    ("Мексика", "Мехико"): "zhivuv_mekhiko",
    ("Мексика", "Монтеррей"): "zhivuv_monterrey",
    ("Мексика", "Морелия"): "zhivuv_moreliya",
    ("Мексика", "Нуэво-Ларедо"): "zhivuv_nuevo_laredo",
    ("Мексика", "Оахака"): "zhivuv_oakhaka",
    ("Мексика", "Пачука"): "zhivuv_pachuka",
    ("Мексика", "Пуэбла"): "zhivuv_puebla",
    ("Мексика", "Рейноса"): "zhivuv_reynosa",
    ("Мексика", "Сальтильо"): "zhivuv_saltillo",
    ("Мексика", "Сан-Луис-Потоси"): "zhivuv_san_luis_potosi",
    ("Мексика", "Санто-Доминго"): "zhivuv_santo_dominigo",
    ("Мексика", "Селаея"): "zhivuv_selaeya",
    ("Мексика", "Сьюдад-Хуарес"): "zhivuv_syuidad_khuares",
    ("Мексика", "Сьюдад-Обрегон"): "zhivuv_syuidad_obregon",
    ("Мексика", "Сьюдад-де-Мехико"): "zhivuv_syuidad_de_mekhiko",
    ("Мексика", "Сьюдад-Вальес"): "zhivuv_syuidad_vales",
    ("Мексика", "Тампиco"): "zhivuv_tampico",
    ("Мексика", "Тепик"): "zhivuv_tepic",
    ("Мексика", "Тепоztlán"): "zhivuv_tepoztlan",
    ("Мексика", "Тихуана"): "zhivuv_tikhuana",
    ("Мексика", "Толука"): "zhivuv_toluka",
    ("Мексика", "Торреон"): "zhivuv_torreon",
    ("Мексика", "Тустла-Гутьеррес"): "zhivuv_tustla_gutierres",
    ("Мексика", "Уруапан"): "zhivuv_uruapan",
    ("Мексика", "Ушмал"): "zhivuv_ushmal",
    ("Мексика", "Четумаль"): "zhivuv_chetumal",
    ("Мексика", "Чиапас"): "zhivuv_chiapas",
    ("Мексика", "Чиуауа"): "zhivuv_chihuahua",
    ("Мексика", "Экатепек"): "zhivuv_ekatepek",
    ("Мексика", "Энсенада"): "zhivuv_ensenada",
    ("Мексика", "Юкатан"): "zhivuv_yukatan",
})
CITY_GROUP_USERNAMES.update({
    ("Италия", "Агридженто"): "@zhivuv_agridzhento",
    ("Италия", "Алессандрия"): "@zhivuv_alessandriya",
    ("Италия", "Анкона"): "@zhivuv_ankona",
    ("Италия", "Аоста"): "@zhivuv_aosta",
    ("Италия", "Апулия"): "@zhivuv_apuliya",
    ("Италия", "Ареццо"): "@zhivuv_arezzo",
    ("Италия", "Асти"): "@zhivuv_asti",
    ("Италия", "Бари"): "@zhivuv_bari",
    ("Италия", "Бергамо"): "@zhivuv_bergamo",
    ("Италия", "Болонья"): "@zhivuv_bolonya",
    ("Италия", "Брешиа"): "@zhivuv_breshia",
    ("Италия", "Бриндизи"): "@zhivuv_brindizi",
    ("Италия", "Верона"): "@zhivuv_verona",
    ("Италия", "Виченца"): "@zhivuv_vichentsa",
    ("Италия", "Генуя"): "@zhivuv_genuya",
    ("Италия", "Империя"): "@zhivuv_imperiya",
    ("Италия", "Кальяри"): "@zhivuv_kalyari",
    ("Италия", "Кампобассо"): "@zhivuv_kampobasso",
    ("Италия", "Катандзаро"): "@zhivuv_katandzaro",
    ("Италия", "Катанья"): "@zhivuv_katanya",
    ("Италия", "Козенца"): "@zhivuv_kozenza",
    ("Италия", "Комо"): "@zhivuv_komo",
    ("Италия", "Кунео"): "@zhivuv_kuneo",
    ("Италия", "ЛʼАкуила"): "@zhivuv_lakuila",
    ("Италия", "Ла-Специя"): "@zhivuv_la_spezia",
    ("Италия", "Лечче"): "@zhivuv_lecce",
    ("Италия", "Ливорно"): "@zhivuv_livorno",
    ("Италия", "Лоди"): "@zhivuv_lodi",
    ("Италия", "Мантова"): "@zhivuv_mantova",
    ("Италия", "Матера"): "@zhivuv_matera",
    ("Италия", "Мессина"): "@zhivuv_messina",
    ("Италия", "Милан"): "@zhivuv_milan",
    ("Италия", "Модена"): "@zhivuv_modena",
    ("Италия", "Неаполь"): "@zhivuv_neapol",
    ("Италия", "Новара"): "@zhivuv_novara",
    ("Италия", "Ольбия"): "@zhivuv_olbiya",
    ("Италия", "Падуя"): "@zhivuv_paduya",
    ("Италия", "Палермо"): "@zhivuv_palermo",
    ("Италия", "Парма"): "@zhivuv_parma",
    ("Италия", "Пезаро"): "@zhivuv_pesaro",
    ("Италия", "Перуджа"): "@zhivuv_perudzha",
    ("Италия", "Пескара"): "@zhivuv_peskara",
    ("Италия", "Пьяченца"): "@zhivuv_pyachentsa",
    ("Италия", "Равенна"): "@zhivuv_ravenna",
    ("Италия", "Рагуза"): "@zhivuv_raguza",
    ("Италия", "Реджо-ди-Калабрия"): "@zhivuv_redzho_di_kalabriya",
    ("Италия", "Рим"): "@zhivuv_rim",
    ("Италия", "Римини"): "@zhivuv_rimini",
    ("Италия", "Салерно"): "@zhivuv_salerno",
    ("Италия", "Сассари"): "@zhivuv_sassari",
})
CITY_GROUP_USERNAMES.update({
    ("Испания", "Аликанте"): "@zhivuv_alikante",
    ("Испания", "Альбасете"): "@zhivuv_albasete",
    ("Испания", "Альмерия"): "@zhivuv_almeriya",
    ("Испания", "Астурия"): "@zhivuv_asturiya",
    ("Испания", "Барселона"): "@zhivuv_barselona",
    ("Испания", "Бадахос"): "@zhivuv_badakhos",
    ("Испания", "Балеарские острова"): "@zhivuv_balearskie_ostrova",
    ("Испания", "Бильбао"): "@zhivuv_bilbao",
    ("Испания", "Бургос"): "@zhivuv_burgos",
    ("Испания", "Вальядолид"): "@zhivuv_valyadolid",
    ("Испания", "Валенсия"): "@zhivuv_valensiya",
    ("Испания", "Вальверде"): "@zhivuv_valverde",
    ("Испания", "Гвадалахара"): "@zhivuv_gvadalakhara",
    ("Испания", "Гранада"): "@zhivuv_granada",
    ("Испания", "Гихон"): "@zhivuv_gikhon",
    ("Испания", "Гирона"): "@zhivuv_girona",
    ("Испания", "Гвадикс"): "@zhivuv_gvadiks",
    ("Испания", "Дон-Бенито"): "@zhivuv_don_benito",
    ("Испания", "Жирона"): "@zhivuv_zhiroна",
    ("Испания", "Замора"): "@zhivuv_zamora",
    ("Испания", "Картахена"): "@zhivuv_kartakhena",
    ("Испания", "Кастельон"): "@zhivuv_kastellon",
    ("Испания", "Касерес"): "@zhivuv_kaseres",
    ("Испания", "Кордова"): "@zhivuv_kordova",
    ("Испания", "Куэнка"): "@zhivuv_kuenka",
    ("Испания", "Ла-Корунья"): "@zhivuv_la_korunya",
    ("Испания", "Ла-Риоха"): "@zhivuv_la_riokha",
    ("Испания", "Лерида"): "@zhivuv_lerida",
    ("Испания", "Логроньо"): "@zhivuv_logronyo",
    ("Испания", "Луго"): "@zhivuv_lugo",
    ("Испания", "Мадрид"): "@zhivuv_madrid",
    ("Испания", "Малага"): "@zhivuv_malaga",
    ("Испания", "Марбелья"): "@zhivuv_marbelia",
    ("Испания", "Мерида"): "@zhivuv_merida",
    ("Испания", "Мостолес"): "@zhivuv_mostoles",
    ("Испания", "Мурсия"): "@zhivuv_mursiya",
    ("Испания", "Овьедо"): "@zhivuv_ovyedo",
    ("Испания", "Оренсе"): "@zhivuv_orense",
    ("Испания", "Паленсия"): "@zhivuv_palensiya",
    ("Испания", "Памплона"): "@zhivuv_pamplona",
    ("Испания", "Понтеведра"): "@zhivuv_pontevedra",
    ("Испания", "Реус"): "@zhivuv_reus",
    ("Испания", "Саламанка"): "@zhivuv_salamanka",
    ("Испания", "Сан-Себастьян"): "@zhivuv_san_sebastian",
    ("Испания", "Сантандер"): "@zhivuv_santander",
    ("Испания", "Севилья"): "@zhivuv_sevilya",
    ("Испания", "Сория"): "@zhivuv_soriya",
    ("Испания", "Таррагона"): "@zhivuv_tarragona",
    ("Испания", "Толедо"): "@zhivuv_toledo",
    ("Испания", "Уэска"): "@zhivuv_ueska",
    ("Испания", "Хаэн"): "@zhivuv_khaen"
})
CITY_GROUP_USERNAMES.update({
    ("Польша", "Альверня"): "@zhivuv_alvernya",
    ("Польша", "Белосток"): "@zhivuv_belostok",
    ("Польша", "Бельско-Бяла"): "@zhivuv_belsko_byala",
    ("Польша", "Быдгощ"): "@zhivuv_bydgoshch",
    ("Польша", "Варшава"): "@zhivuv_varshava",
    ("Польша", "Велюн"): "@zhivuv_velyun",
    ("Польша", "Вроцлав"): "@zhivuv_vrotslav",
    ("Польша", "Гданьск"): "@zhivuv_gdansk",
    ("Польша", "Гдыня"): "@zhivuv_gdynya",
    ("Польша", "Гожув-Велькопольски"): "@zhivuv_gozhuw_velkopolski",
    ("Польша", "Дембица"): "@zhivuv_dembitsa",
    ("Польша", "Еленя-Гура"): "@zhivuv_elenya_gura",
    ("Польша", "Замосць"): "@zhivuv_zamosch",
    ("Польша", "Зелёна-Гура"): "@zhivuv_zelyona_gura",
    ("Польша", "Калиш"): "@zhivuv_kalish",
    ("Польша", "Катовице"): "@zhivuv_katovitse",
    ("Польша", "Кельце"): "@zhivuv_keltse",
    ("Польша", "Константынув-Лодзиньски"): "@zhivuv_konstantynow_lodzinski",
    ("Польша", "Краков"): "@zhivuv_krakov",
    ("Польша", "Кросно"): "@zhivuv_krosno",
    ("Польша", "Легница"): "@zhivuv_legnitsa",
    ("Польша", "Лодзь"): "@zhivuv_lodz",
    ("Польша", "Люблин"): "@zhivuv_lyublin",
    ("Польша", "Любушка"): "@zhivuv_lyubushka",
    ("Польша", "Мальборк"): "@zhivuv_malbork",
    ("Польша", "Мысленице"): "@zhivuv_myslenitse",
    ("Польша", "Нова-Соль"): "@zhivuv_nova_sol",
    ("Польша", "Ольштын"): "@zhivuv_olshtyn",
    ("Польша", "Ополе"): "@zhivuv_opole",
    ("Польша", "Остшешув"): "@zhivuv_ostrzeszow",
    ("Польша", "Пила"): "@zhivuv_pila",
    ("Польша", "Плоцк"): "@zhivuv_plotsk",
    ("Польша", "Познань"): "@zhivuv_poznan",
    ("Польша", "Пшемысль"): "@zhivuv_pshemysl",
    ("Польша", "Пулавы"): "@zhivuv_pulavy",
    ("Польша", "Радом"): "@zhivuv_radom",
    ("Польша", "Рыбник"): "@zhivuv_rybnik",
    ("Польша", "Ряшев"): "@zhivuv_ryashev",
    ("Польша", "Сандомир"): "@zhivuv_sandomir",
    ("Польша", "Седльце"): "@zhivuv_sedltse",
    ("Польша", "Скерневице"): "@zhivuv_skernevitse",
    ("Польша", "Слупск"): "@zhivuv_slupsk",
    ("Польша", "Сохачев"): "@zhivuv_sokhachev",
    ("Польша", "Старгар"): "@zhivuv_stargar",
    ("Польша", "Сувалки"): "@zhivuv_suwalki",
    ("Польша", "Сьрода-Велькопольска"): "@zhivuv_sroda_velkopolska",
    ("Польша", "Тарнув"): "@zhivuv_tarnuv",
    ("Польша", "Томашув-Мазовецки"): "@zhivuv_tomashuv_mazovetski",
    ("Польша", "Торуń"): "@zhivuv_torun",
    ("Польша", "Хелм"): "@zhivuv_khelm"
})
CITY_GROUP_USERNAMES.update({
    ("Польша", "Альверня"): "@zhivuv_alvernya",
    ("Польша", "Белосток"): "@zhivuv_belostok",
    ("Польша", "Бельско-Бяла"): "@zhivuv_belsko_byala",
    ("Польша", "Быдгощ"): "@zhivuv_bydgoshch",
    ("Польша", "Варшава"): "@zhivuv_varshava",
    ("Польша", "Велюн"): "@zhivuv_velyun",
    ("Польша", "Вроцлав"): "@zhivuv_vrotslav",
    ("Польша", "Гданьск"): "@zhivuv_gdansk",
    ("Польша", "Гдыня"): "@zhivuv_gdynya",
    ("Польша", "Гожув-Велькопольски"): "@zhivuv_gozhuw_velkopolski",
    ("Польша", "Дембица"): "@zhivuv_dembitsa",
    ("Польша", "Еленя-Гура"): "@zhivuv_elenya_gura",
    ("Польша", "Замосць"): "@zhivuv_zamosch",
    ("Польша", "Зелёна-Гура"): "@zhivuv_zelyona_gura",
    ("Польша", "Калиш"): "@zhivuv_kalish",
    ("Польша", "Катовице"): "@zhivuv_katovitse",
    ("Польша", "Кельце"): "@zhivuv_keltse",
    ("Польша", "Константынув-Лодзиньски"): "@zhivuv_konstantynow_lodzinski",
    ("Польша", "Краков"): "@zhivuv_krakov",
    ("Польша", "Кросно"): "@zhivuv_krosno",
    ("Польша", "Легница"): "@zhivuv_legnitsa",
    ("Польша", "Лодзь"): "@zhivuv_lodz",
    ("Польша", "Люблин"): "@zhivuv_lyublin",
    ("Польша", "Любушка"): "@zhivuv_lyubushka",
    ("Польша", "Мальборк"): "@zhivuv_malbork",
    ("Польша", "Мысленице"): "@zhivuv_myslenitse",
    ("Польша", "Нова-Соль"): "@zhivuv_nova_sol",
    ("Польша", "Ольштын"): "@zhivuv_olshtyn",
    ("Польша", "Ополе"): "@zhivuv_opole",
    ("Польша", "Остшешув"): "@zhivuv_ostrzeszow",
    ("Польша", "Пила"): "@zhivuv_pila",
    ("Польша", "Плоцк"): "@zhivuv_plotsk",
    ("Польша", "Познань"): "@zhivuv_poznan",
    ("Польша", "Пшемысль"): "@zhivuv_pshemysl",
    ("Польша", "Пулавы"): "@zhivuv_pulavy",
    ("Польша", "Радом"): "@zhivuv_radom",
    ("Польша", "Рыбник"): "@zhivuv_rybnik",
    ("Польша", "Ряшев"): "@zhivuv_ryashev",
    ("Польша", "Сандомир"): "@zhivuv_sandomir",
    ("Польша", "Седльце"): "@zhivuv_sedltse",
    ("Польша", "Скерневице"): "@zhivuv_skernevitse",
    ("Польша", "Слупск"): "@zhivuv_slupsk",
    ("Польша", "Сохачев"): "@zhivuv_sokhachev",
    ("Польша", "Старгар"): "@zhivuv_stargar",
    ("Польша", "Сувалки"): "@zhivuv_suwalki",
    ("Польша", "Сьрода-Велькопольска"): "@zhivuv_sroda_velkopolska",
    ("Польша", "Тарнув"): "@zhivuv_tarnuv",
    ("Польша", "Томашув-Мазовецки"): "@zhivuv_tomashuv_mazovetski",
    ("Польша", "Торуń"): "@zhivuv_torun",
    ("Польша", "Хелм"): "@zhivuv_khelm"
})
CITY_GROUP_USERNAMES.update({
    ("Китай", "Аньшань"): "@zhivuv_anshan",
    ("Китай", "Байинь"): "@zhivuv_baiyin",
    ("Китай", "Баотоу"): "@zhivuv_baotou",
    ("Китай", "Бэйдайхэ"): "@zhivuv_beidaihe",
    ("Китай", "Бэйхай"): "@zhivuv_beihai",
    ("Китай", "Гуанчжоу"): "@zhivuv_guangzhou",
    ("Китай", "Гуйлинь"): "@zhivuv_guilin",
    ("Китай", "Далянь"): "@zhivuv_dalian",
    ("Китай", "Даньдун"): "@zhivuv_dandong",
    ("Китай", "Датун"): "@zhivuv_datong",
    ("Китай", "Дунгуань"): "@zhivuv_dongguan",
    ("Китай", "Ибинь"): "@zhivuv_yibin",
    ("Китай", "Ичан"): "@zhivuv_yichang",
    ("Китай", "Ичунь"): "@zhivuv_yichun",
    ("Китай", "Куньмин"): "@zhivuv_kunming",
    ("Китай", "Ланьчжоу"): "@zhivuv_lanzhou",
    ("Китай", "Лоян"): "@zhivuv_luoyang",
    ("Китай", "Муданьцзян"): "@zhivuv_mudanjiang",
    ("Китай", "Наньнин"): "@zhivuv_nanning",
    ("Китай", "Нанкин"): "@zhivuv_nanjing",
    ("Китай", "Наньчан"): "@zhivuv_nanchang",
    ("Китай", "Пекин"): "@zhivuv_beijing",
    ("Китай", "Паньцзинь"): "@zhivuv_panjin",
    ("Китай", "Сиань"): "@zhivuv_xian",
    ("Китай", "Синин"): "@zhivuv_xining",
    ("Китай", "Сямынь"): "@zhivuv_xiamen",
    ("Китай", "Сучжоу"): "@zhivuv_suzhou",
    ("Китай", "Тайюань"): "@zhivuv_taiyuan",
    ("Китай", "Таншань"): "@zhivuv_tangshan",
    ("Китай", "Тяньцзинь"): "@zhivuv_tianjin",
    ("Китай", "Ухань"): "@zhivuv_wuhan",
    ("Китай", "Уси"): "@zhivuv_wuxi",
    ("Китай", "Фушунь"): "@zhivuv_fushun",
    ("Китай", "Фучжоу"): "@zhivuv_fuzhou",
    ("Китай", "Хайкоу"): "@zhivuv_haikou",
    ("Китай", "Харбин"): "@zhivuv_harbin",
    ("Китай", "Ханчжоу"): "@zhivuv_hangzhou",
    ("Китай", "Хух-Хото"): "@zhivuv_hohhot",
    ("Китай", "Циндао"): "@zhivuv_qingdao",
    ("Китай", "Цзиси"): "@zhivuv_jixi",
    ("Китай", "Цзинань"): "@zhivuv_jinan",
    ("Китай", "Цзыбо"): "@zhivuv_zibo",
    ("Китай", "Чанчунь"): "@zhivuv_changchun",
    ("Китай", "Чанша"): "@zhivuv_changsha",
    ("Китай", "Чанчжоу"): "@zhivuv_changzhou",
    ("Китай", "Чжаньцзян"): "@zhivuv_zhangjiang",
    ("Китай", "Чжэнчжоу"): "@zhivuv_zhengzhou",
    ("Китай", "Чэнду"): "@zhivuv_chengdu",
    ("Китай", "Шанхай"): "@zhivuv_shanghai",
    ("Китай", "Шэньян"): "@zhivuv_shenyang"
})
CITY_GROUP_USERNAMES.update({
    ("Китай", "Аньшань"): "@zhivuv_anshan",
    ("Китай", "Байинь"): "@zhivuv_baiyin",
    ("Китай", "Баотоу"): "@zhivuv_baotou",
    ("Китай", "Бэйдайхэ"): "@zhivuv_beidaihe",
    ("Китай", "Бэйхай"): "@zhivuv_beihai",
    ("Китай", "Гуанчжоу"): "@zhivuv_guangzhou",
    ("Китай", "Гуйлинь"): "@zhivuv_guilin",
    ("Китай", "Далянь"): "@zhivuv_dalian",
    ("Китай", "Даньдун"): "@zhivuv_dandong",
    ("Китай", "Датун"): "@zhivuv_datong",
    ("Китай", "Дунгуань"): "@zhivuv_dongguan",
    ("Китай", "Ибинь"): "@zhivuv_yibin",
    ("Китай", "Ичан"): "@zhivuv_yichang",
    ("Китай", "Ичунь"): "@zhivuv_yichun",
    ("Китай", "Куньмин"): "@zhivuv_kunming",
    ("Китай", "Ланьчжоу"): "@zhivuv_lanzhou",
    ("Китай", "Лоян"): "@zhivuv_luoyang",
    ("Китай", "Муданьцзян"): "@zhivuv_mudanjiang",
    ("Китай", "Наньнин"): "@zhivuv_nanning",
    ("Китай", "Нанкин"): "@zhivuv_nanjing",
    ("Китай", "Наньчан"): "@zhivuv_nanchang",
    ("Китай", "Пекин"): "@zhivuv_beijing",
    ("Китай", "Паньцзинь"): "@zhivuv_panjin",
    ("Китай", "Сиань"): "@zhivuv_xian",
    ("Китай", "Синин"): "@zhivuv_xining",
    ("Китай", "Сямынь"): "@zhivuv_xiamen",
    ("Китай", "Сучжоу"): "@zhivuv_suzhou",
    ("Китай", "Тайюань"): "@zhivuv_taiyuan",
    ("Китай", "Таншань"): "@zhivuv_tangshan",
    ("Китай", "Тяньцзинь"): "@zhivuv_tianjin",
    ("Китай", "Ухань"): "@zhivuv_wuhan",
    ("Китай", "Уси"): "@zhivuv_wuxi",
    ("Китай", "Фушунь"): "@zhivuv_fushun",
    ("Китай", "Фучжоу"): "@zhivuv_fuzhou",
    ("Китай", "Хайкоу"): "@zhivuv_haikou",
    ("Китай", "Харбин"): "@zhivuv_harbin",
    ("Китай", "Ханчжоу"): "@zhivuv_hangzhou",
    ("Китай", "Хух-Хото"): "@zhivuv_hohhot",
    ("Китай", "Циндао"): "@zhivuv_qingdao",
    ("Китай", "Цзиси"): "@zhivuv_jixi",
    ("Китай", "Цзинань"): "@zhivuv_jinan",
    ("Китай", "Цзыбо"): "@zhivuv_zibo",
    ("Китай", "Чанчунь"): "@zhivuv_changchun",
    ("Китай", "Чанша"): "@zhivuv_changsha",
    ("Китай", "Чанчжоу"): "@zhivuv_changzhou",
    ("Китай", "Чжаньцзян"): "@zhivuv_zhangjiang",
    ("Китай", "Чжэнчжоу"): "@zhivuv_zhengzhou",
    ("Китай", "Чэнду"): "@zhivuv_chengdu",
    ("Китай", "Шанхай"): "@zhivuv_shanghai",
    ("Китай", "Шэньян"): "@zhivuv_shenyang"
})
CITY_GROUP_USERNAMES.update({
    ("Великобритания", "Абердин"): "@zhivuv_aberdeen",
    ("Великобритания", "Бат"): "@zhivuv_bath",
    ("Великобритания", "Белфаст"): "@zhivuv_belfast",
    ("Великобритания", "Болтон"): "@zhivuv_bolton",
    ("Великобритания", "Борнмут"): "@zhivuv_bournemouth",
    ("Великобритания", "Брадфорд"): "@zhivuv_bradford",
    ("Великобритания", "Брайтон"): "@zhivuv_brighton",
    ("Великобритания", "Бристоль"): "@zhivuv_bristol",
    ("Великобритания", "Бирмингем"): "@zhivuv_birmingham",
    ("Великобритания", "Вестминстер"): "@zhivuv_westminster",
    ("Великобритания", "Винчестер"): "@zhivuv_winchester",
    ("Великобритания", "Вулверхэмптон"): "@zhivuv_wolverhampton",
    ("Великобритания", "Глазго"): "@zhivuv_glasgow",
    ("Великобритания", "Дарем"): "@zhivuv_durham",
    ("Великобритания", "Дерби"): "@zhivuv_derby",
    ("Великобритания", "Донкастер"): "@zhivuv_doncaster",
    ("Великобритания", "Данди"): "@zhivuv_dundee",
    ("Великобритания", "Ипсуич"): "@zhivuv_ipswich",
    ("Великобритания", "Йорк"): "@zhivuv_york",
    ("Великобритания", "Кембридж"): "@zhivuv_cambridge",
    ("Великобритания", "Ковентри"): "@zhivuv_coventry",
    ("Великобритания", "Кингстон-апон-Халл"): "@zhivuv_hull",
    ("Великобритания", "Колчестер"): "@zhivuv_colchester",
    ("Великобритания", "Ланкастер"): "@zhivuv_lancaster",
    ("Великобритания", "Лидс"): "@zhivuv_leeds",
    ("Великобритания", "Лестер"): "@zhivuv_leicester",
    ("Великобритания", "Ливерпуль"): "@zhivuv_liverpool",
    ("Великобритания", "Линкольн"): "@zhivuv_lincoln",
    ("Великобритания", "Лондон"): "@zhivuv_london",
    ("Великобритания", "Манчестер"): "@zhivuv_manchester",
    ("Великобритания", "Милтон-Кинс"): "@zhivuv_miltonkeynes",
    ("Великобритания", "Ньюкасл-апон-Тайн"): "@zhivuv_newcastle",
    ("Великобритания", "Ньюпорт"): "@zhivuv_newport",
    ("Великобритания", "Норидж"): "@zhivuv_norwich",
    ("Великобритания", "Нортгемптон"): "@zhivuv_northampton",
    ("Великобритания", "Ноттингем"): "@zhivuv_nottingham",
    ("Великобритания", "Оксфорд"): "@zhivuv_oxford",
    ("Великобритания", "Питерборо"): "@zhivuv_peterborough",
    ("Великобритания", "Плимут"): "@zhivuv_plymouth",
    ("Великобритания", "Портсмут"): "@zhivuv_portsmouth",
    ("Великобритания", "Престон"): "@zhivuv_preston",
    ("Великобритания", "Рединг"): "@zhivuv_reading",
    ("Великобритания", "Сандерленд"): "@zhivuv_sunderland",
    ("Великобритания", "Саутгемптон"): "@zhivuv_southampton",
    ("Великобритания", "Саутенд-он-Си"): "@zhivuv_southend",
    ("Великобритания", "Солсбери"): "@zhivuv_salisbury",
    ("Великобритания", "Сток-он-Трент"): "@zhivuv_stoke",
    ("Великобритания", "Суонси"): "@zhivuv_swansea",
    ("Великобритания", "Шеффилд"): "@zhivuv_sheffield"
})
CITY_GROUP_USERNAMES.update({
    ("Португалия", "Авейру"): "@zhivuv_aveiro",
    ("Португалия", "Агуеда"): "@zhivuv_agueda",
    ("Португалия", "Албуфейра"): "@zhivuv_albufeira",
    ("Португалия", "Алмейрин"): "@zhivuv_almeirim",
    ("Португалия", "Амаранте"): "@zhivuv_amarante",
    ("Португалия", "Баррейру"): "@zhivuv_barreiro",
    ("Португалия", "Бежа"): "@zhivuv_beja",
    ("Португалия", "Брага"): "@zhivuv_braga",
    ("Португалия", "Браганса"): "@zhivuv_braganca",
    ("Португалия", "Валенса"): "@zhivuv_valenca",
    ("Португалия", "Вила-ду-Конде"): "@zhivuv_viladoconde",
    ("Португалия", "Вила-Нова-де-Гая"): "@zhivuv_vilanovadegaia",
    ("Португалия", "Вила-Реал"): "@zhivuv_vilareal",
    ("Португалия", "Визеу"): "@zhivuv_viseu",
    ("Португалия", "Висеу"): "@zhivuv_viseu2",
    ("Португалия", "Гимарайнш"): "@zhivuv_guimaraes",
    ("Португалия", "Гондомар"): "@zhivuv_gondomar",
    ("Португалия", "Калдаш-да-Раинья"): "@zhivuv_caldasdarainha",
    ("Португалия", "Кашкайш"): "@zhivuv_cascais",
    ("Португалия", "Коимбра"): "@zhivuv_coimbra",
    ("Португалия", "Лагуш"): "@zhivuv_lagos",
    ("Португалия", "Ламегу"): "@zhivuv_lamego",
    ("Португалия", "Лейрия"): "@zhivuv_leiria",
    ("Португалия", "Лиссабон"): "@zhivuv_lisboa",
    ("Португалия", "Лореш"): "@zhivuv_loures",
    ("Португалия", "Луле"): "@zhivuv_loule",
    ("Португалия", "Мафра"): "@zhivuv_mafra",
    ("Португалия", "Маринья-Гранде"): "@zhivuv_marinhagrande",
    ("Португалия", "Матозиньюш"): "@zhivuv_matosinhos",
    ("Португалия", "Мейранш"): "@zhivuv_meirinhos",
    ("Португалия", "Монтейру"): "@zhivuv_monteiro",
    ("Португалия", "Оейраш"): "@zhivuv_oeiras",
    ("Португалия", "Оливейра-ди-Аземейш"): "@zhivuv_oliveiradazemeis",
    ("Португалия", "Пешу-да-Регуа"): "@zhivuv_pesudaregua",
    ("Португалия", "Порту"): "@zhivuv_porto",
    ("Португалия", "Портиман"): "@zhivuv_portimao",
    ("Португалия", "Пова-де-Варзин"): "@zhivuv_povadevarzim",
    ("Португалия", "Понтеведра"): "@zhivuv_pontevedra",
    ("Португалия", "Сантарен"): "@zhivuv_santarem",
    ("Португалия", "Сетубал"): "@zhivuv_setubal",
    ("Португалия", "Силвеш"): "@zhivuv_silves",
    ("Португалия", "Синтра"): "@zhivuv_sintra",
    ("Португалия", "Тавира"): "@zhivuv_tavira",
    ("Португалия", "Томар"): "@zhivuv_tomar",
    ("Португалия", "Торриш-Новаш"): "@zhivuv_torresnovas",
    ("Португалия", "Торриш-Ведраш"): "@zhivuv_torresvedras",
    ("Португалия", "Фару"): "@zhivuv_faro",
    ("Португалия", "Фигейра-да-Фош"): "@zhivuv_figueiradafoz",
    ("Португалия", "Фуншал"): "@zhivuv_funchal"
})
CITY_GROUP_USERNAMES.update({
    ("Португалия", "Авейру"): "@zhivuv_aveiro",
    ("Португалия", "Агуеда"): "@zhivuv_agueda",
    ("Португалия", "Албуфейра"): "@zhivuv_albufeira",
    ("Португалия", "Алмейрин"): "@zhivuv_almeirim",
    ("Португалия", "Амаранте"): "@zhivuv_amarante",
    ("Португалия", "Баррейру"): "@zhivuv_barreiro",
    ("Португалия", "Бежа"): "@zhivuv_beja",
    ("Португалия", "Брага"): "@zhivuv_braga",
    ("Португалия", "Браганса"): "@zhivuv_braganca",
    ("Португалия", "Валенса"): "@zhivuv_valenca",
    ("Португалия", "Вила-ду-Конде"): "@zhivuv_viladoconde",
    ("Португалия", "Вила-Нова-де-Гая"): "@zhivuv_vilanovadegaia",
    ("Португалия", "Вила-Реал"): "@zhivuv_vilareal",
    ("Португалия", "Визеу"): "@zhivuv_viseu",
    ("Португалия", "Висеу"): "@zhivuv_viseu2",
    ("Португалия", "Гимарайнш"): "@zhivuv_guimaraes",
    ("Португалия", "Гондомар"): "@zhivuv_gondomar",
    ("Португалия", "Калдаш-да-Раинья"): "@zhivuv_caldasdarainha",
    ("Португалия", "Кашкайш"): "@zhivuv_cascais",
    ("Португалия", "Коимбра"): "@zhivuv_coimbra",
    ("Португалия", "Лагуш"): "@zhivuv_lagos",
    ("Португалия", "Ламегу"): "@zhivuv_lamego",
    ("Португалия", "Лейрия"): "@zhivuv_leiria",
    ("Португалия", "Лиссабон"): "@zhivuv_lisboa",
    ("Португалия", "Лореш"): "@zhivuv_loures",
    ("Португалия", "Луле"): "@zhivuv_loule",
    ("Португалия", "Мафра"): "@zhivuv_mafra",
    ("Португалия", "Маринья-Гранде"): "@zhivuv_marinhagrande",
    ("Португалия", "Матозиньюш"): "@zhivuv_matosinhos",
    ("Португалия", "Мейранш"): "@zhivuv_meirinhos",
    ("Португалия", "Монтейру"): "@zhivuv_monteiro",
    ("Португалия", "Оейраш"): "@zhivuv_oeiras",
    ("Португалия", "Оливейра-ди-Аземейш"): "@zhivuv_oliveiradazemeis",
    ("Португалия", "Пешу-да-Регуа"): "@zhivuv_pesudaregua",
    ("Португалия", "Порту"): "@zhivuv_porto",
    ("Португалия", "Портиман"): "@zhivuv_portimao",
    ("Португалия", "Пова-де-Варзин"): "@zhivuv_povadevarzim",
    ("Португалия", "Понтеведра"): "@zhivuv_pontevedra",
    ("Португалия", "Сантарен"): "@zhivuv_santarem",
    ("Португалия", "Сетубал"): "@zhivuv_setubal",
    ("Португалия", "Силвеш"): "@zhivuv_silves",
    ("Португалия", "Синтра"): "@zhivuv_sintra",
    ("Португалия", "Тавира"): "@zhivuv_tavira",
    ("Португалия", "Томар"): "@zhivuv_tomar",
    ("Португалия", "Торриш-Новаш"): "@zhivuv_torresnovas",
    ("Португалия", "Торриш-Ведраш"): "@zhivuv_torresvedras",
    ("Португалия", "Фару"): "@zhivuv_faro",
    ("Португалия", "Фигейра-да-Фош"): "@zhivuv_figueiradafoz",
    ("Португалия", "Фуншал"): "@zhivuv_funchal"
})
CITY_GROUP_USERNAMES.update({
    ("Турецкая Республика Северного Кипра", "Лефкоша"): "@zhivuv_lefkosa",
    ("Турецкая Республика Северного Кипра", "Фамагуста"): "@zhivuv_famagusta",
    ("Турецкая Республика Северного Кипра", "Кирения"): "@zhivuv_kyrenia",
    ("Турецкая Республика Северного Кипра", "Гюзельюрт"): "@zhivuv_guzelyurt",
    ("Турецкая Республика Северного Кипра", "Исkele"): "@zhivuv_iskele",
    ("Турецкая Республика Северного Кипра", "Дикели"): "@zhivuv_dikely",
    ("Турецкая Республика Северного Кипра", "Лапта"): "@zhivuv_lapta",
    ("Турецкая Республика Северного Кипра", "Карпасия"): "@zhivuv_karpasia",
    ("Турецкая Республика Северного Кипра", "Енибогазичи"): "@zhivuv_yenibogazici",
    ("Турецкая Республика Северного Кипра", "Гечиткале"): "@zhivuv_gecitkale",
    ("Турецкая Республика Северного Кипра", "Йени Исале"): "@zhivuv_yeniisale",
    ("Турецкая Республика Северного Кипра", "Аканту"): "@zhivuv_akantu",
    ("Турецкая Республика Северного Кипра", "Бейлербей"): "@zhivuv_beylerbeyi",
    ("Турецкая Республика Северного Кипра", "Беллапаис"): "@zhivuv_bellapais",
    ("Турецкая Республика Северного Кипра", "Еникент"): "@zhivuv_yenikent",
    ("Турецкая Республика Северного Кипра", "Морфу"): "@zhivuv_morphou",
    ("Турецкая Республика Северного Кипра", "Татлысу"): "@zhivuv_tatlısu",
    ("Турецкая Республика Северного Кипра", "Караогланоглу"): "@zhivuv_karaoglanoglu",
    ("Турецкая Республика Северного Кипра", "Йеникой"): "@zhivuv_yenikoy",
    ("Турецкая Республика Северного Кипра", "Богаз"): "@zhivuv_bogaz",
    ("Турецкая Республика Северного Кипра", "Калебурну"): "@zhivuv_kaleburnu",
    ("Турецкая Республика Северного Кипра", "Бафра"): "@zhivuv_bafra",
    ("Турецкая Республика Северного Кипра", "Алсанджак"): "@zhivuv_alsancak",
    ("Турецкая Республика Северного Кипра", "Карапаша"): "@zhivuv_karapasa",
    ("Турецкая Республика Северного Кипра", "Топчукуёй"): "@zhivuv_topcukoy",
    ("Турецкая Республика Северного Кипра", "Доганкой"): "@zhivuv_dogankoy",
    ("Турецкая Республика Северного Кипра", "Каттакой"): "@zhivuv_kattakoy",
    ("Турецкая Республика Северного Кипра", "Масари"): "@zhivuv_masari",
    ("Турецкая Республика Северного Кипра", "Кучукермен"): "@zhivuv_kucukermen",
    ("Турецкая Республика Северного Кипра", "Карапинар"): "@zhivuv_karapinar",
    ("Турецкая Республика Северного Кипра", "Тепедаг"): "@zhivuv_tepeddag",
    ("Турецкая Республика Северного Кипра", "Акдоган"): "@zhivuv_akdogan",
    ("Турецкая Республика Северного Кипра", "Гайреткёй"): "@zhivuv_gayretkoy",
    ("Турецкая Республика Северного Кипра", "Арапкой"): "@zhivuv_arapkoy",
    ("Турецкая Республика Северного Кипра", "Алтынкой"): "@zhivuv_altinkoy",
    ("Турецкая Республика Северного Кипра", "Чаталкой"): "@zhivuv_chatalkoy",
    ("Турецкая Республика Северного Кипра", "Каракурт"): "@zhivuv_karakurt",
    ("Турецкая Республика Северного Кипра", "Башпинар"): "@zhivuv_bashpinar",
    ("Турецкая Республика Северного Кипра", "Еникесит"): "@zhivuv_yenikesit",
    ("Турецкая Республика Северного Кипра", "Кумьялы"): "@zhivuv_kumyali",
    ("Турецкая Республика Северного Кипра", "Балалан"): "@zhivuv_balalan",
    ("Турецкая Республика Северного Кипра", "Туркели"): "@zhivuv_turkeli",
    ("Турецкая Республика Северного Кипра", "Татликой"): "@zhivuv_tatlikoy",
    ("Турецкая Республика Северного Кипра", "Еникент"): "@zhivuv_yenikentkktc",
    ("Турецкая Республика Северного Кипра", "Синди"): "@zhivuv_sindi",
    ("Турецкая Республика Северного Кипра", "Ардхан"): "@zhivuv_ardhan",
    ("Турецкая Республика Северного Кипра", "Саричам"): "@zhivuv_saricam",
    ("Турецкая Республика Северного Кипра", "Пилла"): "@zhivuv_pilla"
})

