services:
  - type: web
    name: zhivuvbot
    env: python
    region: frankfurt
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: python main.py

    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: CHANNEL_ID
        fromEnvVar: CHANNEL_ID
      - key: SAVE_AD_WEBHOOK
        fromEnvVar: SAVE_AD_WEBHOOK
      - key: WEBHOOK_URL
        fromEnvVar: WEBHOOK_URL
      - key: PORT
        fromEnvVar: PORT
